// lib/mockData.js

export const categories = [
  { id: 'all', label: 'All Courses', icon: '◈' },
  { id: 'frontend', label: 'Frontend', icon: '◉' },
  { id: 'backend', label: 'Backend', icon: '◎' },
  { id: 'design', label: 'Design', icon: '◍' },
  { id: 'data', label: 'Data Science', icon: '◌' },
  { id: 'mobile', label: 'Mobile', icon: '◑' },
  { id: 'devops', label: 'DevOps', icon: '◐' },
];

export const courses = [
  {
    id: '1',
    title: 'Advanced React Patterns & Architecture',
    instructor: 'Sarah Chen',
    instructorAvatar: 'SC',
    instructorBio: 'Senior Engineer at Meta with 10+ years building large-scale React applications. Open source contributor to React core.',
    category: 'frontend',
    level: 'Advanced',
    duration: '12h 30m',
    totalLessons: 42,
    rating: 4.9,
    reviews: 2847,
    students: 8432,
    accent: '#E8C547',
    price: '$89',
    tags: ['React', 'TypeScript', 'Performance', 'Testing'],
    progress: 65,
    description: 'Master advanced React concepts including compound components, render props, custom hooks, and state management patterns used at scale in production applications.',
    whatYouLearn: [
      'Build compound component systems',
      'Implement advanced state management patterns',
      'Optimize performance with memoization',
      'Write production-grade TypeScript with React',
      'Test complex component interactions',
      'Architect scalable frontend applications',
    ],
    curriculum: [
      {
        id: 'sec-1',
        title: 'Foundations & Mental Models',
        duration: '2h 15m',
        lessons: [
          { id: 'l1', title: 'Introduction to Advanced Patterns', duration: '12:30', type: 'video', completed: true },
          { id: 'l2', title: 'Component Composition Fundamentals', duration: '18:45', type: 'video', completed: true },
          { id: 'l3', title: 'The React Rendering Model', duration: '22:10', type: 'video', completed: true },
          { id: 'l4', title: 'Quiz: Foundations', duration: '10:00', type: 'quiz', completed: true },
        ],
      },
      {
        id: 'sec-2',
        title: 'Advanced Component Patterns',
        duration: '3h 40m',
        lessons: [
          { id: 'l5', title: 'Compound Components Pattern', duration: '24:30', type: 'video', completed: true },
          { id: 'l6', title: 'Render Props & Children as Functions', duration: '19:15', type: 'video', completed: true },
          { id: 'l7', title: 'Building a Flexible Tabs Component', duration: '32:00', type: 'project', completed: false },
          { id: 'l8', title: 'Higher-Order Components in 2024', duration: '21:45', type: 'video', completed: false },
        ],
      },
      {
        id: 'sec-3',
        title: 'Custom Hooks Architecture',
        duration: '2h 55m',
        lessons: [
          { id: 'l9', title: 'Custom Hook Design Principles', duration: '17:20', type: 'video', completed: false },
          { id: 'l10', title: 'State Synchronization Patterns', duration: '28:10', type: 'video', completed: false },
          { id: 'l11', title: 'Building a Data Fetching Hook', duration: '35:00', type: 'project', completed: false },
        ],
      },
      {
        id: 'sec-4',
        title: 'Performance Optimization',
        duration: '3h 40m',
        lessons: [
          { id: 'l12', title: 'Understanding Re-renders', duration: '20:00', type: 'video', completed: false },
          { id: 'l13', title: 'useMemo & useCallback Mastery', duration: '25:30', type: 'video', completed: false },
          { id: 'l14', title: 'Code Splitting Strategies', duration: '18:45', type: 'video', completed: false },
          { id: 'l15', title: 'Profiling & Debugging', duration: '22:00', type: 'video', completed: false },
        ],
      },
    ],
  },
  {
    id: '2',
    title: 'Node.js Microservices at Scale',
    instructor: 'Marcus Rivera',
    instructorAvatar: 'MR',
    instructorBio: 'CTO at Infrastack. Speaker at NodeConf. 15 years building distributed systems.',
    category: 'backend',
    level: 'Intermediate',
    duration: '18h 20m',
    totalLessons: 64,
    rating: 4.8,
    reviews: 1923,
    students: 5821,
    accent: '#4ECDC4',
    price: '$99',
    tags: ['Node.js', 'Docker', 'Kubernetes', 'gRPC'],
    progress: 30,
    description: 'Design and deploy production-ready microservices with Node.js, Docker, and Kubernetes. Covers service discovery, circuit breakers, event sourcing, and observability.',
    whatYouLearn: [
      'Design microservice architectures',
      'Implement service-to-service communication',
      'Deploy with Docker and Kubernetes',
      'Build resilient systems with circuit breakers',
      'Set up distributed tracing',
      'Monitor and observe microservices',
    ],
    curriculum: [
      {
        id: 'sec-1',
        title: 'Microservices Fundamentals',
        duration: '3h 00m',
        lessons: [
          { id: 'l1', title: 'Monolith vs Microservices', duration: '20:00', type: 'video', completed: true },
          { id: 'l2', title: 'Service Decomposition Strategies', duration: '25:30', type: 'video', completed: true },
          { id: 'l3', title: 'Setting Up Your First Service', duration: '30:00', type: 'project', completed: false },
        ],
      },
      {
        id: 'sec-2',
        title: 'Communication Patterns',
        duration: '4h 20m',
        lessons: [
          { id: 'l4', title: 'REST vs gRPC vs Message Queues', duration: '22:00', type: 'video', completed: false },
          { id: 'l5', title: 'Implementing RabbitMQ', duration: '35:00', type: 'video', completed: false },
          { id: 'l6', title: 'Event-Driven Architecture', duration: '28:00', type: 'video', completed: false },
        ],
      },
    ],
  },
  {
    id: '3',
    title: 'Design Systems with Figma & Code',
    instructor: 'Anya Petrova',
    instructorAvatar: 'AP',
    instructorBio: 'Design Lead at Stripe. Creator of the Figma Design Tokens plugin with 200k+ users.',
    category: 'design',
    level: 'Beginner',
    duration: '9h 45m',
    totalLessons: 38,
    rating: 4.9,
    reviews: 3451,
    students: 12340,
    accent: '#C47A52',
    price: '$79',
    tags: ['Figma', 'Design Tokens', 'CSS', 'Accessibility'],
    progress: 90,
    description: 'Create comprehensive design systems from scratch, bridging the gap between design and development with tokens, components, and documentation.',
    whatYouLearn: [
      'Build a component library in Figma',
      'Implement design tokens',
      'Create accessible components',
      'Document design decisions',
      'Bridge design and development workflows',
      'Version and maintain design systems',
    ],
    curriculum: [
      {
        id: 'sec-1',
        title: 'Design System Foundations',
        duration: '2h 00m',
        lessons: [
          { id: 'l1', title: 'What Makes a Great Design System', duration: '15:00', type: 'video', completed: true },
          { id: 'l2', title: 'Atomic Design Principles', duration: '20:00', type: 'video', completed: true },
          { id: 'l3', title: 'Setting Up Your Figma Workspace', duration: '25:00', type: 'video', completed: true },
        ],
      },
    ],
  },
  {
    id: '4',
    title: 'Machine Learning with Python',
    instructor: 'Dr. James Okafor',
    instructorAvatar: 'JO',
    instructorBio: 'PhD in Machine Learning from MIT. Former researcher at DeepMind. Author of "Practical ML".',
    category: 'data',
    level: 'Intermediate',
    duration: '24h 10m',
    totalLessons: 88,
    rating: 4.7,
    reviews: 4201,
    students: 15820,
    accent: '#A855F7',
    price: '$119',
    tags: ['Python', 'TensorFlow', 'scikit-learn', 'Neural Networks'],
    progress: 0,
    description: 'From linear regression to deep neural networks, build a complete understanding of machine learning algorithms and their practical applications.',
    whatYouLearn: [
      'Understand ML algorithms deeply',
      'Build neural networks from scratch',
      'Work with real-world datasets',
      'Deploy ML models to production',
      'Implement computer vision projects',
      'Build NLP applications',
    ],
    curriculum: [
      {
        id: 'sec-1',
        title: 'Python for ML',
        duration: '3h 30m',
        lessons: [
          { id: 'l1', title: 'NumPy & Pandas Essentials', duration: '30:00', type: 'video', completed: false },
          { id: 'l2', title: 'Data Visualization with Matplotlib', duration: '25:00', type: 'video', completed: false },
        ],
      },
    ],
  },
  {
    id: '5',
    title: 'React Native: Build iOS & Android Apps',
    instructor: 'Leila Hassan',
    instructorAvatar: 'LH',
    instructorBio: 'Mobile Lead at Shopify. Core contributor to React Navigation. Google Developer Expert.',
    category: 'mobile',
    level: 'Intermediate',
    duration: '15h 00m',
    totalLessons: 52,
    rating: 4.8,
    reviews: 1542,
    students: 6200,
    accent: '#F59E0B',
    price: '$94',
    tags: ['React Native', 'Expo', 'iOS', 'Android'],
    progress: 15,
    description: 'Build beautiful, performant cross-platform mobile apps with React Native and Expo. Ships to iOS and Android from a single codebase.',
    whatYouLearn: [
      'Build cross-platform mobile apps',
      'Navigate between screens smoothly',
      'Work with device APIs',
      'Implement offline-first features',
      'Optimize app performance',
      'Publish to App Store & Play Store',
    ],
    curriculum: [
      {
        id: 'sec-1',
        title: 'Getting Started with React Native',
        duration: '2h 30m',
        lessons: [
          { id: 'l1', title: 'Setting Up Expo Development', duration: '20:00', type: 'video', completed: true },
          { id: 'l2', title: 'Core Components Overview', duration: '25:00', type: 'video', completed: false },
        ],
      },
    ],
  },
  {
    id: '6',
    title: 'DevOps & CI/CD with GitHub Actions',
    instructor: 'Tobias Müller',
    instructorAvatar: 'TM',
    instructorBio: 'Platform Engineer at Netflix. DevOps consultant with 12 years experience.',
    category: 'devops',
    level: 'Advanced',
    duration: '11h 45m',
    totalLessons: 44,
    rating: 4.6,
    reviews: 987,
    students: 3750,
    accent: '#10B981',
    price: '$84',
    tags: ['GitHub Actions', 'Docker', 'Terraform', 'AWS'],
    progress: 0,
    description: 'Automate your entire software delivery pipeline. From testing to deployment, build robust CI/CD workflows that scale with your team.',
    whatYouLearn: [
      'Design CI/CD pipelines from scratch',
      'Automate testing and deployments',
      'Manage infrastructure as code',
      'Set up monitoring and alerting',
      'Implement GitOps workflows',
      'Secure your deployment pipeline',
    ],
    curriculum: [
      {
        id: 'sec-1',
        title: 'CI/CD Fundamentals',
        duration: '2h 00m',
        lessons: [
          { id: 'l1', title: 'What is CI/CD?', duration: '15:00', type: 'video', completed: false },
          { id: 'l2', title: 'Your First GitHub Actions Workflow', duration: '30:00', type: 'project', completed: false },
        ],
      },
    ],
  },
];

export const userProfile = {
  name: 'Alex Morgan',
  email: 'alex.morgan@email.com',
  avatar: 'AM',
  title: 'Full Stack Developer',
  joinDate: 'March 2023',
  streak: 12,
  totalHours: 47,
  completedCourses: 3,
  certificates: 2,
  xp: 8450,
  level: 'Intermediate',
  achievements: [
    { id: 'a1', title: 'First Course', icon: '🎯', description: 'Completed your first course', earned: true },
    { id: 'a2', title: '7-Day Streak', icon: '🔥', description: 'Learned 7 days in a row', earned: true },
    { id: 'a3', title: 'Speed Learner', icon: '⚡', description: 'Completed a course in under 3 days', earned: true },
    { id: 'a4', title: 'Night Owl', icon: '🦉', description: 'Studied after midnight 5 times', earned: false },
    { id: 'a5', title: 'Perfect Score', icon: '💯', description: 'Aced every quiz in a course', earned: false },
    { id: 'a6', title: 'Contributor', icon: '🌟', description: 'Left 10 helpful comments', earned: false },
  ],
  recentActivity: [
    { type: 'lesson', text: 'Completed "Compound Components Pattern"', course: 'Advanced React', time: '2 hours ago' },
    { type: 'quiz', text: 'Scored 95% on React Foundations Quiz', course: 'Advanced React', time: '3 hours ago' },
    { type: 'streak', text: 'Extended learning streak to 12 days', course: null, time: '1 day ago' },
    { type: 'lesson', text: 'Started "Service Decomposition Strategies"', course: 'Node.js Microservices', time: '2 days ago' },
    { type: 'cert', text: 'Earned certificate for Design Systems', course: 'Design Systems', time: '5 days ago' },
  ],
};

export const getCourseById = (id) => courses.find((c) => c.id === id);

export const getEnrolledCourses = () => courses.filter((c) => c.progress > 0);

export const getLessonById = (courseId, lessonId) => {
  const course = getCourseById(courseId);
  if (!course) return null;
  for (const section of course.curriculum) {
    const lesson = section.lessons.find((l) => l.id === lessonId);
    if (lesson) return { lesson, section, course };
  }
  return null;
};
